#!/usr/bin/env python3
"""
Project Setup Script
====================
Run this after cloning the repository to set up everything.

Usage:
    python setup.py              # Interactive setup
    python setup.py --defaults   # Use default values (localhost)
    python setup.py --docker     # Setup for Docker environment
"""
import os
import sys
import subprocess
import argparse
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
ENV_FILE = PROJECT_ROOT / ".env"
ENV_EXAMPLE = PROJECT_ROOT / ".env.example"


# Default configuration
DEFAULT_CONFIG = {
    "DATABASE_URL": "postgresql+asyncpg://postgres:postgres@localhost:5432/fixed_asset_db",
    "SECRET_KEY": "dev-secret-key-change-in-production-use-long-random-string",
    "CORS_ORIGINS": '["http://localhost:3000","http://localhost:5173","http://127.0.0.1:3000"]',
    "ACCESS_TOKEN_EXPIRE_MINUTES": "1440",
    "REFRESH_TOKEN_EXPIRE_DAYS": "7",
}

DOCKER_CONFIG = {
    "DATABASE_URL": "postgresql+asyncpg://postgres:postgres@db:5432/fixed_asset_db",
    "SECRET_KEY": "dev-secret-key-change-in-production-use-long-random-string",
    "CORS_ORIGINS": '["http://localhost:3000","http://localhost:5173","http://127.0.0.1:3000"]',
    "ACCESS_TOKEN_EXPIRE_MINUTES": "1440",
    "REFRESH_TOKEN_EXPIRE_DAYS": "7",
}


def print_header(text: str):
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60)


def print_step(step: int, text: str):
    print(f"\n[{step}] {text}")
    print("-" * 40)


def run_command(cmd: str, description: str = None, shell: bool = True) -> bool:
    """Run a shell command and return success status."""
    if description:
        print(f"  → {description}")
    try:
        result = subprocess.run(cmd, shell=shell, check=True, capture_output=False)
        return True
    except subprocess.CalledProcessError as e:
        print(f"  ✗ Command failed: {cmd}")
        return False
    except FileNotFoundError:
        print(f"  ✗ Command not found: {cmd.split()[0]}")
        return False


def check_prerequisites() -> dict:
    """Check if required tools are installed."""
    print_step(1, "Checking prerequisites")

    checks = {
        "python": "python --version",
        "poetry": "poetry --version",
        "git": "git --version",
    }

    results = {}
    for tool, cmd in checks.items():
        try:
            result = subprocess.run(
                cmd, shell=True, capture_output=True, text=True
            )
            if result.returncode == 0:
                version = result.stdout.strip() or result.stderr.strip()
                print(f"  ✓ {tool}: {version}")
                results[tool] = True
            else:
                print(f"  ✗ {tool}: not found")
                results[tool] = False
        except Exception:
            print(f"  ✗ {tool}: not found")
            results[tool] = False

    return results


def create_env_file(config: dict, interactive: bool = False):
    """Create .env file with configuration."""
    print_step(2, "Creating .env file")

    if ENV_FILE.exists():
        print(f"  ! .env file already exists at {ENV_FILE}")
        if interactive:
            response = input("  Overwrite? (y/N): ").strip().lower()
            if response != 'y':
                print("  → Keeping existing .env file")
                return
        else:
            print("  → Keeping existing .env file (use --force to overwrite)")
            return

    final_config = config.copy()

    if interactive:
        print("\n  Configure database connection:")
        print(f"  Default: {config['DATABASE_URL']}")

        db_host = input("  Database host [localhost]: ").strip() or "localhost"
        db_port = input("  Database port [5432]: ").strip() or "5432"
        db_name = input("  Database name [fixed_asset_db]: ").strip() or "fixed_asset_db"
        db_user = input("  Database user [postgres]: ").strip() or "postgres"
        db_pass = input("  Database password [postgres]: ").strip() or "postgres"

        final_config["DATABASE_URL"] = f"postgresql+asyncpg://{db_user}:{db_pass}@{db_host}:{db_port}/{db_name}"

    # Write .env file
    env_content = f"""# Fixed Asset Verification API - Environment Configuration
# Generated by setup.py

# Database connection (PostgreSQL with asyncpg)
DATABASE_URL={final_config['DATABASE_URL']}

# JWT Secret Key (change this in production!)
SECRET_KEY={final_config['SECRET_KEY']}

# CORS allowed origins (JSON array)
CORS_ORIGINS={final_config['CORS_ORIGINS']}

# Token expiration
ACCESS_TOKEN_EXPIRE_MINUTES={final_config['ACCESS_TOKEN_EXPIRE_MINUTES']}
REFRESH_TOKEN_EXPIRE_DAYS={final_config['REFRESH_TOKEN_EXPIRE_DAYS']}
"""

    with open(ENV_FILE, 'w') as f:
        f.write(env_content)

    print(f"  ✓ Created .env file")
    print(f"  → Database: {final_config['DATABASE_URL'].split('@')[1] if '@' in final_config['DATABASE_URL'] else 'configured'}")


def install_dependencies():
    """Install Python dependencies using Poetry."""
    print_step(3, "Installing dependencies with Poetry")

    if not run_command("poetry install", "Installing packages..."):
        print("\n  Alternative: Try running manually:")
        print("    poetry install")
        return False

    print("  ✓ Dependencies installed")
    return True


def setup_database(skip_seed: bool = False):
    """Set up database tables and seed data."""
    print_step(4, "Setting up database")

    print("  → Creating database tables...")
    if not run_command("poetry run python reset_db.py", "Running reset_db.py"):
        print("\n  ! Database setup failed. Make sure PostgreSQL is running.")
        print("  ! Check your DATABASE_URL in .env file.")
        return False

    if not skip_seed:
        print("\n  → Seeding mock data...")
        if not run_command("poetry run python seed_mock_data.py", "Running seed_mock_data.py"):
            print("  ! Seeding failed, but tables were created.")
            return True

    print("  ✓ Database setup complete")
    return True


def print_summary():
    """Print setup completion summary."""
    print_header("SETUP COMPLETE!")

    print("""
  Next steps:

  1. Start the development server:
     poetry run uvicorn main:app --reload

  2. Open API documentation:
     http://localhost:8000/docs

  3. Test login credentials:
     ┌──────────┬───────────────────────────┬─────────────┐
     │ Role     │ Email                     │ Password    │
     ├──────────┼───────────────────────────┼─────────────┤
     │ ADMIN    │ admin@company.com         │ admin123    │
     │ AUDITOR  │ john.auditor@company.com  │ auditor123  │
     │ OWNER    │ mike.developer@company.com│ owner123    │
     │ VIEWER   │ viewer@company.com        │ viewer123   │
     └──────────┴───────────────────────────┴─────────────┘

  4. Useful commands:
     poetry run python reset_db.py --seed   # Reset database
     poetry run pytest                      # Run tests
""")


def main():
    parser = argparse.ArgumentParser(
        description="Set up the Fixed Asset Verification API project"
    )
    parser.add_argument(
        "--defaults",
        action="store_true",
        help="Use default configuration (non-interactive)"
    )
    parser.add_argument(
        "--docker",
        action="store_true",
        help="Configure for Docker environment"
    )
    parser.add_argument(
        "--skip-db",
        action="store_true",
        help="Skip database setup"
    )
    parser.add_argument(
        "--skip-seed",
        action="store_true",
        help="Skip seeding mock data"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing .env file"
    )

    args = parser.parse_args()

    print_header("Fixed Asset API - Project Setup")

    # Check prerequisites
    prereqs = check_prerequisites()
    if not prereqs.get("poetry"):
        print("\n  ! Poetry is required. Install it from: https://python-poetry.org/")
        sys.exit(1)

    # Choose config
    if args.docker:
        config = DOCKER_CONFIG
        interactive = False
    elif args.defaults:
        config = DEFAULT_CONFIG
        interactive = False
    else:
        config = DEFAULT_CONFIG
        interactive = True

    # Create .env file
    create_env_file(config, interactive=interactive)

    # Install dependencies
    if not install_dependencies():
        print("\n  ! Setup incomplete. Fix errors and try again.")
        sys.exit(1)

    # Setup database
    if not args.skip_db:
        if not setup_database(skip_seed=args.skip_seed):
            print("\n  ! Database setup failed. You can run it manually later:")
            print("    poetry run python reset_db.py --seed")

    # Print summary
    print_summary()


if __name__ == "__main__":
    main()
