#!/bin/bash
# =============================================================================
# AWS EC2 One-Click Deployment Script
# =============================================================================
#
# This script sets up everything on a fresh Ubuntu EC2 instance:
# - Docker & Docker Compose
# - Clone repo and start containers
# - Configure firewall
#
# Usage:
#   1. Launch Ubuntu 22.04 EC2 instance (t2.small or larger)
#   2. SSH into the instance
#   3. Run: curl -sSL https://raw.githubusercontent.com/kredoworks/fixed-asset-api/v2/deploy/ec2-deploy.sh | bash
#
#   Or manually:
#   wget https://raw.githubusercontent.com/kredoworks/fixed-asset-api/v2/deploy/ec2-deploy.sh
#   chmod +x ec2-deploy.sh
#   ./ec2-deploy.sh
#
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_header() {
    echo -e "\n${GREEN}============================================${NC}"
    echo -e "${GREEN}  $1${NC}"
    echo -e "${GREEN}============================================${NC}\n"
}

print_step() {
    echo -e "${YELLOW}→ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Configuration
REPO_URL="https://github.com/kredoworks/fixed-asset-api.git"
BRANCH="v2"
APP_DIR="/opt/fixed-asset-api"
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
SECRET_KEY=$(openssl rand -base64 64 | tr -dc 'a-zA-Z0-9' | head -c 64)

print_header "Fixed Asset API - EC2 Deployment"

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    print_error "Please run with sudo: sudo ./ec2-deploy.sh"
    exit 1
fi

# =============================================================================
# Step 1: Update system
# =============================================================================
print_step "Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
print_success "System updated"

# =============================================================================
# Step 2: Install Docker
# =============================================================================
print_step "Installing Docker..."

if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh

    # Add ubuntu user to docker group
    usermod -aG docker ubuntu 2>/dev/null || true

    # Start Docker
    systemctl enable docker
    systemctl start docker
    print_success "Docker installed"
else
    print_success "Docker already installed"
fi

# =============================================================================
# Step 3: Install Docker Compose
# =============================================================================
print_step "Installing Docker Compose..."

if ! command -v docker-compose &> /dev/null; then
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    print_success "Docker Compose installed"
else
    print_success "Docker Compose already installed"
fi

# =============================================================================
# Step 4: Clone repository
# =============================================================================
print_step "Cloning repository..."

if [ -d "$APP_DIR" ]; then
    print_step "Removing existing installation..."
    cd /opt
    rm -rf "$APP_DIR"
fi

git clone -b "$BRANCH" "$REPO_URL" "$APP_DIR"
cd "$APP_DIR"
print_success "Repository cloned to $APP_DIR"

# =============================================================================
# Step 5: Create environment file
# =============================================================================
print_step "Creating environment configuration..."

cat > .env << EOF
# Generated by ec2-deploy.sh on $(date)
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=fixed_asset_db
SECRET_KEY=$SECRET_KEY
CORS_ORIGINS=["*"]
ACCESS_TOKEN_EXPIRE_MINUTES=1440
REFRESH_TOKEN_EXPIRE_DAYS=7
EOF

chmod 600 .env
print_success "Environment file created"

# =============================================================================
# Step 6: Configure firewall
# =============================================================================
print_step "Configuring firewall..."

# Allow SSH, HTTP, HTTPS, and API port
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 8000/tcp
ufw --force enable
print_success "Firewall configured"

# =============================================================================
# Step 7: Build and start containers
# =============================================================================
print_step "Building and starting containers..."

docker-compose pull
docker-compose build --no-cache
docker-compose up -d db

# Wait for database to be ready
print_step "Waiting for database to be ready..."
sleep 10

# Initialize database
print_step "Initializing database..."
docker-compose run --rm db-init

# Start API
docker-compose up -d api

print_success "Containers started"

# =============================================================================
# Step 8: Verify deployment
# =============================================================================
print_step "Verifying deployment..."
sleep 5

if curl -s http://localhost:8000/health > /dev/null 2>&1; then
    print_success "API is running!"
else
    # Check if endpoint exists, try docs
    if curl -s http://localhost:8000/docs > /dev/null 2>&1; then
        print_success "API is running!"
    else
        print_error "API health check failed. Check logs with: docker-compose logs api"
    fi
fi

# =============================================================================
# Print summary
# =============================================================================
PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "YOUR_EC2_IP")

print_header "Deployment Complete!"

echo -e "
${GREEN}Your API is now running!${NC}

  API URL:        http://$PUBLIC_IP:8000
  API Docs:       http://$PUBLIC_IP:8000/docs
  Health Check:   http://$PUBLIC_IP:8000/health

${YELLOW}Test Credentials:${NC}
  ┌──────────┬───────────────────────────┬─────────────┐
  │ Role     │ Email                     │ Password    │
  ├──────────┼───────────────────────────┼─────────────┤
  │ ADMIN    │ admin@company.com         │ admin123    │
  │ AUDITOR  │ john.auditor@company.com  │ auditor123  │
  │ OWNER    │ mike.developer@company.com│ owner123    │
  │ VIEWER   │ viewer@company.com        │ viewer123   │
  └──────────┴───────────────────────────┴─────────────┘

${YELLOW}Useful Commands:${NC}
  cd $APP_DIR
  docker-compose logs -f api     # View API logs
  docker-compose logs -f db      # View DB logs
  docker-compose restart api     # Restart API
  docker-compose down            # Stop all
  docker-compose up -d           # Start all

${YELLOW}Environment file:${NC} $APP_DIR/.env

${RED}IMPORTANT:${NC}
  - Change default passwords in production!
  - Set up SSL/HTTPS with nginx or AWS ALB
  - Configure proper CORS_ORIGINS for your frontend

"
